## Problem: Create two NumPy arrays, A and B, of size 5x5 filled with random integers. Write a Python function to:


### Find the element-wise sum of A and B.


In [2]:
import numpy as np

In [9]:
A=np.random.randint(5,size=(5,5))

In [10]:
A

array([[1, 2, 1, 4, 3],
       [4, 1, 0, 0, 2],
       [0, 1, 4, 2, 0],
       [4, 1, 1, 3, 2],
       [2, 0, 1, 4, 3]])

In [11]:
B=np.random.randint(5,size=(5,5))

In [12]:
B

array([[0, 3, 3, 3, 3],
       [2, 3, 4, 0, 2],
       [1, 2, 0, 1, 4],
       [0, 0, 3, 2, 2],
       [2, 1, 0, 3, 2]])

In [13]:
sum=A+B
sum

array([[1, 5, 4, 7, 6],
       [6, 4, 4, 0, 4],
       [1, 3, 4, 3, 4],
       [4, 1, 4, 5, 4],
       [4, 1, 1, 7, 5]])

## Compute the dot product of A and B.


In [14]:
dot_product=np.dot(A,B)

In [15]:
dot_product

array([[11, 14, 23, 21, 25],
       [ 6, 17, 16, 18, 18],
       [ 6, 11, 10,  8, 22],
       [ 7, 19, 25, 25, 28],
       [ 7, 11, 18, 24, 24]])

## Calculate the mean and standard deviation of each row in A and B.

In [28]:
A

array([[1, 2, 1, 4, 3],
       [4, 1, 0, 0, 2],
       [0, 1, 4, 2, 0],
       [4, 1, 1, 3, 2],
       [2, 0, 1, 4, 3]])

In [29]:
B

array([[0, 3, 3, 3, 3],
       [2, 3, 4, 0, 2],
       [1, 2, 0, 1, 4],
       [0, 0, 3, 2, 2],
       [2, 1, 0, 3, 2]])

In [33]:
mean_A=np.mean(A,axis=1)

In [ ]:
mean_A

In [ ]:
std_A=np.std(A,axis=1)

In [ ]:
std_A

In [34]:
mean_B=np.mean(B,axis=1)

In [38]:
std_B=np.std(B,axis=1)

In [39]:
std_B

array([1.2       , 1.32664992, 1.356466  , 1.2       , 1.0198039 ])